# =============================================================================
# Inventaire Ansible — Redis HA avec Sentinel
# =============================================================================

[redis_master]
master ansible_host=192.168.1.158 ansible_user=compute

[redis_replicas]
replica1 ansible_host=192.168.1.140 ansible_user=compute
replica2 ansible_host=192.168.1.159 ansible_user=compute

[redis_all:children]
redis_master
redis_replicas
